//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid DistrictId { get; set; }
        public int StateId { get; set; }
    }
}
