//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext
    {
        public Context()
            : base("name=Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<District> Districts { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<FileFileType> FileFileTypes { get; set; }
        public DbSet<FileType> FileTypes { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<Header> Headers { get; set; }
        public DbSet<Outcome> Outcomes { get; set; }
        public DbSet<OutcomeUnit> OutcomeUnits { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Standard> Standards { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<StrandDomain> StrandDomains { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<TeachingDate> TeachingDates { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<UnitFile> UnitFiles { get; set; }
        public DbSet<UnitStandard> UnitStandards { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserProfileSchool> UserProfileSchools { get; set; }
        public DbSet<UserProfileUnit> UserProfileUnits { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
