//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileType
    {
        public FileType()
        {
            this.FileFileTypes = new HashSet<FileFileType>();
        }
    
        public int Id { get; set; }
        public string FileTypeName { get; set; }
    
        public virtual ICollection<FileFileType> FileFileTypes { get; set; }
    }
}
