//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.FileFileTypes = new HashSet<FileFileType>();
            this.TeachingDates = new HashSet<TeachingDate>();
            this.UnitFiles = new HashSet<UnitFile>();
        }
    
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public int ContentLength { get; set; }
        public string StoragePath { get; set; }
        public int UserProfile_Id { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<FileFileType> FileFileTypes { get; set; }
        public virtual ICollection<TeachingDate> TeachingDates { get; set; }
        public virtual ICollection<UnitFile> UnitFiles { get; set; }
    }
}
