//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public Header()
        {
            this.Standards = new HashSet<Standard>();
        }
    
        public int Id { get; set; }
        public string Header1 { get; set; }
        public string Header2 { get; set; }
        public string Header3 { get; set; }
        public string Header4 { get; set; }
        public int StrandDomain_Id { get; set; }
    
        public virtual StrandDomain StrandDomain { get; set; }
        public virtual ICollection<Standard> Standards { get; set; }
    }
}
