//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public Standard()
        {
            this.UnitStandards = new HashSet<UnitStandard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public int Header_Id { get; set; }
    
        public virtual Header Header { get; set; }
        public virtual ICollection<UnitStandard> UnitStandards { get; set; }
    }
}
