//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Districts = new HashSet<District>();
            this.Schools = new HashSet<School>();
            this.StrandDomains = new HashSet<StrandDomain>();
        }
    
        public int Id { get; set; }
        public string StateName { get; set; }
        public string ShortForm { get; set; }
    
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<StrandDomain> StrandDomains { get; set; }
    }
}
