//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.OutcomeUnits = new HashSet<OutcomeUnit>();
            this.UnitFiles = new HashSet<UnitFile>();
            this.UnitStandards = new HashSet<UnitStandard>();
            this.UnitUserProfiles = new HashSet<UnitUserProfile>();
        }
    
        public System.Guid Id { get; set; }
        public string UnitName { get; set; }
        public string Description { get; set; }
        public int Grade_Id { get; set; }
        public int Subject_Id { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual ICollection<OutcomeUnit> OutcomeUnits { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<UnitFile> UnitFiles { get; set; }
        public virtual ICollection<UnitStandard> UnitStandards { get; set; }
        public virtual ICollection<UnitUserProfile> UnitUserProfiles { get; set; }
    }
}
