//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.OutcomeUnits = new HashSet<OutcomeUnit>();
            this.UnitFiles = new HashSet<UnitFile>();
            this.UnitGrades = new HashSet<UnitGrade>();
            this.UnitStandards = new HashSet<UnitStandard>();
            this.UnitSubjects = new HashSet<UnitSubject>();
        }
    
        public System.Guid Id { get; set; }
        public string UnitName { get; set; }
        public string Description { get; set; }
        public int UserProfile_Id { get; set; }
    
        public virtual ICollection<OutcomeUnit> OutcomeUnits { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UnitFile> UnitFiles { get; set; }
        public virtual ICollection<UnitGrade> UnitGrades { get; set; }
        public virtual ICollection<UnitStandard> UnitStandards { get; set; }
        public virtual ICollection<UnitSubject> UnitSubjects { get; set; }
    }
}
