//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubject
    {
        public int Id { get; set; }
        public int UserProfile_Id { get; set; }
        public int Subject_Id { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
