//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedagogyWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Files = new HashSet<File>();
            this.Units = new HashSet<Unit>();
            this.UserGrades = new HashSet<UserGrade>();
            this.UserProfileSchools = new HashSet<UserProfileSchool>();
            this.UserSubjects = new HashSet<UserSubject>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual ICollection<UserGrade> UserGrades { get; set; }
        public virtual ICollection<UserProfileSchool> UserProfileSchools { get; set; }
        public virtual ICollection<UserSubject> UserSubjects { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
